# -*- coding: utf-8 -*-
"""task2_data_processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1314ex05BL8uwB8cA8Nwbj4ijZsKkR08A
"""

import pandas as pd
import json

# 1. Load JSON file
file_path = "trends_20260405.json"

with open(file_path, "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print(f"Loaded {len(df)} rows")

# 2. Clean Data

# Remove duplicates
df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))

# Remove missing values
df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

# Convert types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove low score (<5)
df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

# Remove extra spaces
df["title"] = df["title"].str.strip()

# 3. Save CSV
df.to_csv("trends_clean.csv", index=False)

print(f"Saved {len(df)} rows to trends_clean.csv")

# Category summary
print("\nStories per category:")
print(df["category"].value_counts())

from google.colab import files
files.upload()

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

file_path = "trends_20260405.json"

import pandas as pd

df = pd.read_json("trends_20260405 (1).json")
print(df.head())

# Remove duplicates
df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))

# Remove missing values
df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

# Convert types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove low score (<5)
df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

# Remove extra spaces
df["title"] = df["title"].str.strip()

# Save CSV
df.to_csv("trends_clean.csv", index=False)
print(f"Saved {len(df)} rows to trends_clean.csv")

# Category summary
print("\nStories per category:")
print(df["category"].value_counts())

import pandas as pd

# 1. Load data
df = pd.read_json("trends_20260405 (1).json")
print(df.head())

# 2.

def get_category(title):
    title = title.lower()

    if "ai" in title or "tech" in title or "software" in title:
        return "technology"
    elif "sport" in title:
        return "sports"
    elif "science" in title:
        return "science"
    elif "movie" in title or "music" in title:
        return "entertainment"
    else:
        return "worldnews"

df["category"] = df["title"].apply(get_category)

# 3. Cleaning start
df = df.drop_duplicates(subset="post_id")
print("After removing duplicates:", len(df))

df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

df["title"] = df["title"].str.strip()

def get_category(title):
    title = str(title).lower()
    if "ai" in title or "tech" in title:
        return "technology"
    elif "sport" in title:
        return "sports"
    elif "science" in title:
        return "science"
    elif "world" in title:
        return "worldnews"
    else:
        return "general"

df["category"] = df["title"].apply(get_category)

# 4. Save CSV
df.to_csv("trends_clean.csv", index=False)
print(f"Saved {len(df)} rows")

# 5. Category summary
print("\nStories per category:")
print(df["category"].value_counts())

from google.colab import files
files.download("trends_clean.csv")

with open("task2_data_processing.py", "w") as f:
    f.write("""PASTE YOUR FULL CODE HERE""")

